<div class="front">
<h1>Mapuj své výkony!</h1>
<p>Díky <strong>TrekMap</strong> budeš teď mít přehled ve svých trasách na běh, cyklotrasách nebo pěších výletech.</p>
</div>

<div class="clothesline">
<div class="column firstcol">

<h2>Krok 1: <strong>Přidej se</strong></h2>
<p>Začít je snadné! Není potřeba ani registrace. Stačí, pokud máš univerzální účet <a href="{link Default:help}#openid" title="Co je OpenID?">OpenID</a>.</p>

<p class="figure">
<img src="{$baseUri}img/openid.png" alt="logo OpenID">
</p>

<p class="go"><a href="{link Account:login}">Přihlásit se</a> <strong>&raquo;</strong></p>

</div>
<div class="column secondcol">

<h2>Krok 2: <strong>Mapuj</strong></h2>
<p>Vyznač na mapu svou trasu, ulož ji a pak už k ní jen přidávej své výkony. Statistiky se počítají samy!</p>

<p class="go"><a href="{link Default:demo}">Zkusit si mapování</a> <strong>&raquo;</strong></p>

</div>
<div class="column thirdcol">

<h2>Krok 3: <strong>Pochlub se!</strong></h2>
<p>Trasy se objeví na tvém veřejném profilu. Ten můžeš poslat kamarádům a pochlubit se svými nejnovějšími rekordy nebo posledním výletem za krásami našich hor.</p>
<p class="go"><a href="{link Track:user $profile}">Příklad profilu</a> <strong>&raquo;</strong></p>

</div>
</div>
