<div class="clothesline">
<div class="column" id="left">
<h1>Demo</h1>
<p>Zde si můžeš vyzkoušet zaznamenávání trasy do mapy.
Můžeš ji dokonce jednorázově uložit a získat na ni odkaz (bude fungovat i nezaregistrovaným).</p>

<div id="trekmap-menu"><button id="trekmap-toggle-mode">Změnit režim</button></div>
<button id="trekmap-save">Uložit</button>

<p>Kilometrů: <strong id="trekmap-total-distance"></strong></p>

<p>
	<label for="trekmap-milestones">Zobrazovat kilometráž:</label>
	<input id="trekmap-milestones" type="checkbox" checked>
</p>

<p>
	<label for="trekmap-altitude">Výškový profil:</label>
	<input id="trekmap-altitude" type="checkbox" checked>
</p>

</div>
<div class="column" id="right">

<div id="trekmap" class="map-large"></div>
<div id="trekmap-altitude-chart"></div>

</div>
</div>
