<h1>{$title}</h1>

<ul class="nav toc">
    <li><a href="#openid">Co je to OpenID?</a> &darr;</li>
    <li><a href="#gravatar">Gravatar</a> &darr;</li>
    <li><a href="#javascript">JavaScript</a> &darr;</li>
</ul>

<h2 id="openid">Co je to OpenID?</h2>
{include '../@help.openid.phtml'}

<h2 id="gravatar">Gravatar</h2>
{include '../@help.gravatar.phtml'}

<h2 id="javascript">JavaScript</h2>

<p>K tomu, aby TrekMap správně běžel, je třeba podpora pro jazyk JavaScript. Jak si JavaScript zapnout?</p>

<p class="eye-catcher">
	<noscript>JavaScript nyní <strong>nefunguje</strong>.</noscript>
	<script>document.write('JavaScript <strong>jede v pořádku</strong>!');</script>
</p>

<h3><img src="{$baseUri}img/browser-ie7.png" alt="Logo Internet Exploreru" class="float-left">
Internet Explorer 6&nbsp;a vyšší</h3>
<p>Nabídka <kbd>Nástroje → Možnosti Internetu → Zabezpečení → Zóna:
Internet → Vlastní úroveň → Skriptování → Aktivní skriptování
→</kbd> zatrhnout <kbd>Povolit</kbd>.</p>

<h3><img src="{$baseUri}img/browser-firefox.png" alt="Logo Mozilla Firefoxu" class="float-left">
Firefox 1.5&nbsp;a vyšší</h3>
<p>Nabídka <kbd>Nástroje → Možnosti… → Obsah →</kbd> zatrhnout
<kbd>Povolit JavaScript</kbd>.</p>

<h3><img src="{$baseUri}img/browser-opera.png" alt="Logo Opery" class="float-left">
Opera 8.5&nbsp;a vyšší</h3>
<p>Nabídka <kbd>Nástroje → Nastavení… → Pokročilé volby → Obsah
→</kbd> zatrhnout<kbd> Povolit JavaScript</kbd>.</p>
