<h1>{$title}</h1>

<h2>TrekMap je služba, kde si můžeš uložit mapu jakékoliv své krátké trasy</h2>

<p>Nejen pro běžce, cyklisty, chodce, turisty, běžkaře a bruslaře, ale třeba i pro jezdce na koních a vodáky.</p>


<h2>Kdo za TrekMap stojí?</h2>

<p>Za myšlenkou a technickým zpracováním TrekMap stojí <a href="{link Track:user, $littlemaple}">Honza Javorek</a>.</p>

<h2>Jak to vzniklo</h2>

<p>TrekMap je aplikace, která vznikla na základě mé bakalářské práce z roku 2009 pro <a
href="http://www.fit.vutbr.cz">FIT</a> <a href="http://www.vutbr.cz">VUT</a>
v Brně pod vedením pana <a href="http://www.fit.vutbr.cz/~hruska/">Prof. Ing. Tomáše Hrušky, CSc.</a>
Zadání <a href="http://blog.javorek.net/bakalarka">je na mém blogu</a>.</p>

<h2>TrekMap se mi líbí! Chci mu pomoci!</h2>

<ul>
	<li><a href="{link Account:login}">používej ho</a></li>

	<li>řekni o něm svým kamarádům</li>

	<li>odkazuj na něj ze svých stránek</li>

	<li>piš o něm na svém blogu</li>

	<li>piš o něm v novinách, časopisech, …</li>
</ul>

<h2>Pro techniky</h2>

<p>TrekMap běží na HTML4.01, PHP{=phpversion()}, JavaScriptu a frameworku <a href="http://www.nettephp.com">Nette</a> s <a href="http://www.dibiphp.com">dibi</a>. Systém podporuje <a href="http://www.openid.net/">OpenID</a>, <a href="http://www.gravatar.com/">Gravatar</a> a <a href="http://www.microformats.org/">mikroformáty</a>.
Využitá API: <a href="http://www.amapy.cz/">Amapy.cz</a>, <a href="http://www.vyskopis.cz/">Výškopis ČR</a>, <a href="http://www.geonames.org/">GeoNames</a>, <a href="http://code.google.com/intl/cs/apis/chart/">Google Chart API</a>, <a href="http://code.google.com/intl/cs/apis/maps/documentation/services.html#Geocoding">Google Maps API</a>,
<a href="http://code.google.com/intl/cs/apis/maps/documentation/staticmaps/">Google Static Maps API</a>. Ikonky jsou z <a href="http://tango.freedesktop.org/">projektu Tango</a>, <a href="http://www.pinvoke.com/">Fugue Icons</a> a <a href="http://semlabs.co.uk/journal/sem-labs-web-blog-icon-pack">SEM Labs Web Blog Icon Pack</a>.</p>

<h2>Chci Honzovi napsat něco hezkého</h2>

<p>Hezkého, škaredého, inspirativního, …</p>

<div class="businesscard vcard">
	<h3 class="fn n"><span class="given-name">Honza</span> <span>Javorek</span></h3>

	<p class="photo"><img src="{$baseUri}img/honza-javorek.jpg"
	alt="zamrzlý Honza Javorek ve Finském Oulu"></p>

    <p class="contacts">
    <strong>Web: </strong><a href="http://honza.javorek.net/"
	class="url">honza.javorek.net</a><br>

	<strong>E-mail: </strong><a href="mailto:honza&#64;javorek.net"
	class="email">honza&#64;<!---->javorek­.net</a><br>

	<strong>Jabber: </strong><a class="url"
	href="xmpp:littlemaple&#64;jabber.cz">littlemaple<!-- jabber -->&#64;<!-- jabber -->jabber.cz</a><br>
	</p>
</div>
