<h1>Jak to říci…</h1>

<p>My z&nbsp;IT tomu říkáme chyba 404.&nbsp;Tak nějak se stalo, že tato stránka,
<em>{=$_SERVER['REQUEST_URI']}</em>, <strong>neexistuje</strong>.</p>

<h2>Proč ale?</h2>

<ul>
    <li>Nemohlo se stát, že máš <strong>překlep</strong> v&nbsp;adrese?</li>

    <li>Odkaz, kvůli němuž jsi tady, je již jednoduše
    <strong>zastaralý</strong>.</li>

    <li>Odkaz, kvůli němuž jsi tady, unikl mému levému či pravému oku a je
    prostě <strong>chybný</strong>. Vynadej mi na {$email}.&nbsp;Díky!</li>
</ul>

<h2>Hmm… Co s&nbsp;tím?</h2>

<p>Záchranou je <a href="{link Home:}">úvodní strana</a> webu.</p>
