<h1>Jak to øíci…</h1>

<p>My z&nbsp;IT tomu øíkáme chyba 404.&nbsp;Tak nìjak se stalo, že tato stránka,
<em>{=$_SERVER['REQUEST_URI']}</em>, <strong>neexistuje</strong>.</p>

<h2>Proè ale?</h2>

<ul>
    <li>Nemohlo se stát, že máš <strong>pøeklep</strong> v&nbsp;adrese?</li>

    <li>Odkaz, kvùli nìmuž jsi tady, je již jednoduše
    <strong>zastaralý</strong>.</li>

    <li>Odkaz, kvùli nìmuž jsi tady, unikl mému levému èi pravému oku a je
    prostì <strong>chybný</strong>. Vynadej mi na {$email}.&nbsp;Díky!</li>
</ul>

<h2>Hmm… Co s&nbsp;tím?</h2>

<p>Záchranou je <a href="{link Home:}">úvodní strana</a> webu.</p>
