<p>Jednoduše řečeno, <strong>univerzální přihlašování</strong>. Nemusíš si pro TrekMap registrovat nějakou přezdívku a vymýšlet posté další heslo &mdash; využij účtu, který již dávno máš! Jedním z poskytovatelů OpenID je například i <a href="http://www.seznam.cz/">Seznam.cz</a>. Máš-li účet na Seznamu, <a href="http://napoveda.seznam.cz/cz/login/openid/">můžeš se s ním přihlásit i zde</a> na TrekMap:</p>

<p class="figure">
<img src="{$baseUri}img/seznam-oid.png" alt="Např. pokud máš e-mail jan.novak@seznam.cz, tvoje OpenID je jan.novak.id.seznam.cz.">
</p>

<p>Aby bylo možné přihlásit se na TrekMap, musíš ve svém OpenID poskytnout <strong>své celé jméno</strong>. Pokud používáš Seznam.cz, v <a href="http://ucet.seznam.cz/">nastavení účtu</a> musíš nejdříve vyplnit <kbd>jméno</kbd> a <kbd>příjmení</kbd> a označit je jako <strong>veřejný údaj</strong>.</p>

<p class="figure">
<img src="{$baseUri}img/openid.png" alt="Logo OpenID">
</p>

<h3>Kdo podporuje OpenID?</h3>

<div class="figure">
<table>
	<tr><th>Služba</th><th>Jak poznám své OpenID</th></tr>
	<tr><td><a href="http://www.seznam.cz">Seznam.cz</a></td><td><kbd>@</kbd> ve svém e-mailu nahradím za <kbd>.id.</kbd></td></tr>
	<tr><td><a href="http://www.myspace.com">MySpace</a></td><td><kbd>myspace.com/<em>jmeno</em></kbd></td></tr>
	<tr><td><a href="http://www.blogger.com">Blogger</a></td><td><kbd><em>jmeno</em>.blogspot.com</kbd></td></tr>
	<tr><td><a href="http://www.flickr.com">Flickr</a></td><td><kbd>www.flickr.com/photos/<em>jmeno</em></kbd></td></tr>
</table>
</div>

<p>a další&hellip; Svoje OpenID si ale můžeš zřídit u spousty jiných registrátorů &mdash jako třeba na <a href="http://www.myopenid.com/">myOpenID.com</a>.</p>
