<div class="clothesline">
<div class="column" id="left">

<p class="eye-catcher"><strong id="tm-distance-driver"></strong> km</p>

<fieldset id="tm-geocoding-driver">
	<legend>Kde to bude?</legend>
	<input type="text">
	<button>Najít</button>
</fieldset>

{if $mode != TrekMap::VIEW}
<fieldset>
	<legend>Tvorba trasy</legend>
	<button id="tm-editor-toggle">Změnit režim</button>
	<button id="tm-reset-button">Vymazat</button>
	<button id="tm-undo-button">Zpět</button>
	<button id="tm-finish-loop-button">Spojit do okruhu</button>
	<button id="tm-same-way-back-button">Stejnou cestou zpět</button>
	<button id="tm-focus-button">Vidět celou trasu</button>
	<button id="tm-save-button">Uložit</button>
</fieldset>
{/if}

<fieldset>
	<legend>Nastavení</legend>
	
	<table>
		<tr><th>
			<label for="tm-milestones-toggle">Zobrazovat kilometráž:</label>
		</th><td>
			<input id="tm-milestones-toggle" type="checkbox" checked>
		</td></tr>
		
		<tr><th>
			<label for="tm-center-toggle">Automaticky centrovat:</label>
		</th><td>
			<input id="tm-center-toggle" type="checkbox" checked>
		</td></tr>
	
		<tr><th>
			<label for="tm-altitude-toggle">Výškový profil:</label>
		</th><td>
			<input id="tm-altitude-toggle" type="checkbox" checked>
		</td></tr>
	</table>
</fieldset>

</div>
<div class="column" id="right">

<div id="trekmap"></div>
<div id="tm-altitude-driver"></div>

</div>
</div>
