		<h1>{$title}</h1>
		
		{$form->render('begin')}
		<fieldset>
			{if $form->getErrors()}
			{$form->render('errors')}
			{/if}
			<table>
				<tr><th>{$form['openid']->label}</th><td class="openid">{$form['openid']->control}</td></tr>
				<tr><td colspan="2">{$form['send']->control}</td></tr>
			</table>
		</fieldset>
		{$form->render('end')}
		
		<h2>Co je to OpenID?</h2>
		{include '../@help.openid.phtml'}
