{contentType application/rss+xml; charset=utf-8}
<<?php ?>?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
	<channel>
		<title>{$title}</title>
		<link>{link Xml:rss}</link>
		<description>{$description}</description>
		<language>cs</language>

		{foreach $items as $item}<item>
		{foreach $item as $key => $value}
	<{!$key}>{$value}</{!$key}>
		{/foreach}</item>
		{/foreach}
		
	</channel>
</rss>
